#generated by newprogram

#AM_CFLAGS=-Wall -Wextra -O2 -D_GNU_SOURCE=1
# Set up initially to use GDB, change to optimised afterward.
AM_CFLAGS=-Wall -Wextra -g -O0 -D_GNU_SOURCE=1

bin_PROGRAMS=exe%s

exe%s_SOURCES=src%s

man_MANS=man%s

# next lines to be hand edited
# send <whatever> to $(prefix)/share/
thr%sdir=$(datadir)/exe%s
thr%s_DATA=
# ensure that man%s and any other config files get put in the tarball.
# also stops `make distcheck` bringing an error.
EXTRA_DIST=man%s
