.TH "NEWPROGRAM" 1 "2017-09-08" "Linux Programmer's Manual"


.SH NAME

.P
\fBnewprogram\fR \- creates a new C programming project.

.SH SYNOPSIS

.P
\fBnewprogram\fR [option] Project/program name.

.SH DESCRIPTION

.P
\fBnewprogram\fR creates the program directory in the user designated
programs directory, creates the Makefile.am for use with autotools, and
depending on options selected, can copy stub files into the projects dir
and can link software into that dir also.

.P
If the project name is given as \fBsomeprog\fR the created directory will
be \fBSomeprog/q\fR and the main sourcefile named in \fIMakefile.am\fR will
be \fBsomeprog.c\fR and the manpage will be named as \fBsomeprog.1\fR. This
will happen regardless of the case used at invocation.

.SH OPTIONS

.TP
 \fB\-h\fR, \fB\-\-help\fR
Print help information and exit.

.TP
 \fB\-\-depends\fR, \fB\-d\fR \fIsoftware_name\fR or '\fIswname1 swname2 ... swnameN\fR'
The option may be invoked multiple times to name multiple software
dependencies, or may be done in a quote protected list.

Also, software that exists as named header and C files may be designated
as \fIswname.c+h\fR. During processing the names \fIswname.c\fR and
\fIswname.h\fR will be generated.

Sofwares so named that exist in the designated source components library
will be hard linked into the project directory.

.TP
 \fB\-\-with\-options\fR, \fB\-o\fR
The files \fIgopt.c\fR and \fIgopt.h\fR will be automatically included in
the software dependencies list. If they reside in the designated
\fIStubs\fR directory, they will copied into the project dir, not linked.

.TP
 \fB\-\-extra\-dist\fR, \fB\-x\fR \fIfile\fR or '\fIfile1 file2 ... fileN\fR'
These are file(s) to be named in the \fB???_DATA=\fR and \fBEXTRA_DIST\fR
parts of \fIMakefile.am\fR.

As above a series of files may be entered by a series of invocations of
the option or entered in a quote protected list.

.SH NOTES

.P
\fB1.\fR On first run configuration files will be installed.

.P
The configuration dir is \fI$HOME.config/newprogam\fR and the files are
\fIpaths.cfg\fR and \fIam.mak\fR.

.P
The file \fIpaths.cfg\fR contains the name of the programs dir, the
program \fBStubs\fR dir and the source library \fBComponents\fR dir. You
should edit this file to conform to your needs. The other file
\fIam.mak\fR  forms the basis of the \fIMakefile.am\fR. You should not
edit this unless you know what you are doing.

.P
\fB2.\fR In the distribution or tarball there is a file
\fIboilerplate.zip\fR.

.P
Unzip this and move the files to your \fBStubs\fR directory.

.P
Any files listed in \fB_SOURCES\fR in the Makefile.am will if found in
the \fBStubs\fR dir, be copied into the project directory. Those found
in \fBComponents\fR dir will be hard linked there instead.

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man newprogram.t2t
